# Generated by Django 5.0.7 on 2024-08-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='discord_id',
            field=models.CharField(choices=[('bearer', 'Bearer'), ('oauth2', 'Oauth2'), ('id', 'ID')], default='0', max_length=255, unique=True, verbose_name='Token Type'),
        ),
    ]
